### ISSUE TITLE
Use ShadcnUI's OTP input element for our auth flow

### ISSUE THREAD

**Issue by KMKoushik** [oss-apps/split-pro#33]
https://ui.shadcn.com/docs/components/input-otp

**Comment by anantraghuvanshi** [comment]
Since we receive 5 characters in the OTP, I think the option we could go for be :
<img width="455" alt="image" src="https://github.com/oss-apps/split-pro/assets/43936308/9f0a6463-fd47-48e4-a332-d742b2dd4ac2">
or
<img width="469" alt="image" src="https://github.com/oss-apps/split-pro/assets/43936308/0707750c-846c-4df8-8bd7-ed0241c40655">
I would like to hear you on this @KMKoushik

**Comment by KMKoushik** [comment]
> Since we receive 5 characters in the OTP, I think the option we could go for be :
> 
> 
> I would like to hear you on this @KMKoushik 

That sounds good!

**Comment by anantraghuvanshi** [comment]
Since, we are modifying this page, what I was thinking should be updated is the text "
We have sent an email with the OTP. Please check your inbox" where the plain email could be something like testXXXX@XXXil.com. Would that be okay @KMKoushik ?

**Comment by KMKoushik** [comment]
> Since, we are modifying this page, what I was thinking should be updated is the text " We have sent an email with the OTP. Please check your inbox" where the plain email could be something like [testXXXX@XXXil.com](mailto:testXXXX@XXXil.com). Would that be okay @KMKoushik ?

I also don't mind putting the entire email!

**Comment by anantraghuvanshi** [comment]
#38 Fixes this. Kindly look into this. @KMKoushik
