### ISSUE TITLE
Feature Request: Ability to add non-email members to a group

### ISSUE THREAD

**Issue by mtaanquist** [oss-apps/split-pro#67]
To be able to quickly make an expense split, I'd love the ability to add 'fictional' users to a group. Right now, if I were out with a group of people that aren't already users, it could take longer time to get them all to sign up, than if I were to just add a bunch of persons to a group and do the splitting there.

If this is already an option, and I just can't see it, feel free to close the issue.

**Comment by KMKoushik** [comment]
@mtaanquist You don't have to wait for the users to sign up. You can just add the email and start adding the expense. When they signup they will see the expenses that you added. 

Lemme know if that answers your question!

**Comment by mtaanquist** [comment]
Fair enough, that's a decent workaround. I do still think it'd be a decent enough idea to just be able to create them as a name first, and then if you do group up again later, you could always add an email address to them.

Some people do have long or strange email addresses that can be odd to spell out. If it is something that fits in your vision of the app, and at all possible with the table structure, I'd be happy to build out a PR over the summer holidays.

It might also help make it a bit easier for people looking to self-host (which is an interest of mine) to not have to sort out a mail server as well.

I appreciate the quick response.

**Comment by KMKoushik** [comment]
@mtaanquist  Splitpro is designed to be a an app where you can share expenses with your friends. 

But I totally get your point, to make self host easy, I'll make the email invite optional for self host. You'll still have to enter email but it won't send any email or anything. 

Btw I'm using [unsend.dev](https://unsend.dev) for sending email. It's my other OSS project which uses AWS SES to send emails in neat way. Since it's open source you can self host it as well (also will have generous free plan). Then again I'll make completely optional so it's easy to self host!

**Comment by mtaanquist** [comment]
Appreciate the feedback, KM, and thanks for the quick replies. 😊

**Comment by gabeclarke** [comment]
I thought I’d emphasize this feature is also really important if the goal is only to track expenses split between groups where the groups aren’t interested in adding an app or keeping track of it themselves. As a workaround I currently have to create dummy email addresses. Love the app and really appreciate the open source element!

**Comment by KMKoushik** [comment]
this is really not the scope splitpro currently, i can come back to this in future
